# wasm-tools compose -c config.yml -o composed.wasm calculator.wasm

search-paths:
  - operator/target/wasm32-wasi/release
  - calculator/target/wasm32-wasi/release

instantiations:
  $input:
    arguments:
     local:calculator/add: operator