[package]
name = "add"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "local:calculator"
target = { path = "../../wit", world = "add-operator"}

[package.metadata.component.dependencies]
