[package]
name = "operator"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = { version = "0.9.0", default_features = false }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "local:calculator"
target = { path = "../wit", world = "operator"}

[package.metadata.component.dependencies]
